# Generated by Django 3.1.6 on 2021-02-21 14:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0003_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('company_contact', ckeditor_uploader.fields.RichTextUploadingField()),
                ('director_statement', ckeditor_uploader.fields.RichTextUploadingField()),
                ('faqs', ckeditor_uploader.fields.RichTextUploadingField()),
                ('email_host', models.CharField(max_length=100)),
                ('email_password', models.CharField(max_length=100)),
                ('login_logo', models.ImageField(upload_to='products/')),
                ('cart_logo', models.ImageField(upload_to='products/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
