# Generated by Django 3.1.6 on 2021-02-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0006_setting_company_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('Blue', 'Blue'), ('Black', 'Black'), ('Red', 'Red'), ('White', 'White'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Green', 'Green'), ('Gray', 'Gray')], max_length=100),
        ),
    ]
