# Generated by Django 3.1.6 on 2021-02-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0009_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image_add',
            field=models.ImageField(blank=True, upload_to='uploads/images'),
        ),
    ]
