# Generated by Django 3.1.6 on 2021-02-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0010_auto_20210222_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='updated_on',
            new_name='last_modified',
        ),
    ]
