# Generated by Django 3.1.6 on 2021-02-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='company_video_title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
