# Generated by Django 3.1.6 on 2021-02-23 08:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0015_setting_cart_logo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='cart_logo_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Shop with us!!'),
        ),
    ]
