# Generated by Django 3.1.6 on 2021-02-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0019_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
