# Generated by Django 3.1.6 on 2021-02-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0021_auto_20210223_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
