# Generated by Django 3.1.6 on 2021-02-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0022_auto_20210223_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='company_video',
            field=models.FileField(blank=True, default='', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='company_video_title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
